# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpyg.proto\x12\'com.github.inpefess.tptp2graph.pygproto\"Z\n\x04\x44\x61ta\x12\t\n\x01x\x18\x01 \x03(\x03\x12\x11\n\tedge_attr\x18\x02 \x03(\x03\x12\x19\n\x11\x65\x64ge_index_source\x18\x03 \x03(\x03\x12\x19\n\x11\x65\x64ge_index_target\x18\x04 \x03(\x03\x42\x02P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _DATA._serialized_start=54
  _DATA._serialized_end=144
# @@protoc_insertion_point(module_scope)
